services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment-management-app
    ports:
      - "8080:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - recruitment-network

networks:
  recruitment-network:
    driver: bridge 