services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev -- --host
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173" # Vite dev server port
    networks:
      - recruitment-network

networks:
  recruitment-network:
    driver: bridge 