services:
  client:
    build:
      context: ./client
      target: production
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - recruitment-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      target: production
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env.production
    environment:
      - JWT_SECRET_KEY=your_production_secret_key_change_me
    networks:
      - recruitment-network
    restart: unless-stopped

networks:
  recruitment-network:
    driver: bridge 