version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment-management-app
    ports:
      - "8080:80"
    restart: unless-stopped
    # For local development with hot reload
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - recruitment-network

  # Mock API service - Uncomment if needed
  # mock-api:
  #   image: node:20-alpine
  #   container_name: recruitment-management-api
  #   working_dir: /app
  #   volumes:
  #     - ./mock-api:/app
  #   command: sh -c "npm install && npm start"
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - recruitment-network

networks:
  recruitment-network:
    driver: bridge 